export interface GalleryImage {
  id: string
  src: string
  title: string
  prompt: string
  model: string
  date: string
  year: number
}

export const galleryImages: GalleryImage[] = [
  {
    "id": "1",
    "src": "/art/13-astronaut-skating-san-francisco-gemini.jpg",
    "title": "Happy Skater",
    "prompt": "Astronaut happily skating in the streets of San Francisco",
    "model": "Gemini 3 Pro (Nano Banana)",
    "date": "November 29, 2025",
    "year": 2025
  },
  {
    id: "2",
    src: "/art/01-astronaut-playing-basketball.webp",
    title: "Cosmic Basketball Player",
    prompt: "Astronaut playing basketball #aiimages #ai #basketball #astronaut",
    model: "Dall-E",
    date: "October 21, 2024",
    year: 2024,
  },
  {
    id: "3",
    src: "/art/02-astronaut-on-horse.webp",
    title: "Cosmic Rider",
    prompt: "Astronaut riding a horse #ai #general #aiimages",
    model: "Dall-E",
    date: "October 19, 2024",
    year: 2024,
  },
  {
    id: "4",
    src: "/art/03-astronaut-skateboarding-nyc.webp",
    title: "Urban Skateboarder",
    prompt: "Astronaut skating in the middle of NYC traffic #ai #aiimage #generativeart",
    model: "Dall-E",
    date: "May 3, 2023",
    year: 2023,
  },
  {
    id: "5",
    src: "/art/04-astronaut-laundry-archimboldo.webp",
    title: "Surreal Laundry",
    prompt: "An astronaut doing laundry in archimboldo style. Generated by Dall-E",
    model: "Dall-E",
    date: "June 24, 2022",
    year: 2022,
  },
  {
    id: "6",
    src: "/art/05-astronaut-watching-netflix.webp",
    title: "Relaxation Mode",
    prompt: "An astronaut who is watching Netflix. Generated by Dall-E",
    model: "Dall-E",
    date: "June 19, 2022",
    year: 2022,
  },
  {
    id: "7",
    src: "/art/06-astronaut-morning-routine.webp",
    title: "Morning Preparations",
    prompt: "An astronaut who just woke up from sleep and is getting ready for the next adventure. Generated by Dall-E",
    model: "Dall-E",
    date: "June 18, 2022",
    year: 2022,
  },
  {
    id: "8",
    src: "/art/07-astronaut-sleepless-night.webp",
    title: "Sleepless in Space",
    prompt: "A photo of Astronaut who is sleepless and yet trying to sleep on the bed. Generated by Dall-E",
    model: "Dall-E",
    date: "June 16, 2022",
    year: 2022,
  },
  {
    id: "9",
    src: "/art/08-astronaut-backpain-space-station.webp",
    title: "Healing Journey",
    prompt: "A photo of Astronaut with backpain trying to sleep. Generated by Dall-E",
    model: "Dall-E",
    date: "June 16, 2022",
    year: 2022,
  },
  {
    id: "10",
    src: "/art/09-astronaut-hospital-backpain.webp",
    title: "Medical Intervention",
    prompt: "Astronaut in hospital with backpain. Generated by Dall-E",
    model: "Dall-E",
    date: "June 16, 2022",
    year: 2022,
  },
  {
    id: "11",
    src: "/art/10-astronaut-falling-milky-way.webp",
    title: "Falling Through the Galaxy",
    prompt: "A photo of an astronaut falling deep into the Milky way galaxy. Generated by Dall-E",
    model: "Dall-E",
    date: "June 16, 2022",
    year: 2022,
  },
  {
    id: "12",
    src: "/art/11-astronaut-iphone-stage.webp",
    title: "Historic Presentation",
    prompt: "A photo of an astronaut introducing the iPhone to the world for the first time on stage. Generated by Dall-E",
    model: "Dall-E",
    date: "June 16, 2022",
    year: 2022,
  },
  {
    id: "13",
    src: "/art/12-astronaut-skating-san-francisco.webp",
    title: "Urban Skater",
    prompt: "An image generated by Dall-E where it shows a visibly happy Astronaut in their full suit and helmet skating in the streets of San Francisco",
    model: "Dall-E",
    date: "June 16, 2022",
    year: 2022,
  }
  
]
